// ITERANDO UMA SEQUÊCIA DE NÚMEROS PARES

function* gerarNumerosPares(max) {
    for(let i = 0; i <= max; i += 2) {
        yield i
    }
}

const gen = gerarNumerosPares(10)

for (numero of gen) {
    console.log(numero)
}

/*
    DEFINIMOS UMA FUNÇÃO GERADORA GERARNUMEROSPARES(MAX) QUE ACEITA UM PARÂMETRO MAX, QUE É O NÚMERO MÁXIMO QUE QUEREMOS GERAR. 

    DENTRO DA FUNÇÃO GERADORA, USAMOS UM LOOP FOR PARA ITERAR DE 0 ATÉ MAX EM INCREMENTOS DE 2. 

    A CADA ITERAÇÃO DO LOOP, UTILIZAMOS A INSTRUÇÃO YIELD PARA PAUSAR A EXECUÇÃO E RETORNAR O NÚMERO ATUAL. 

    EM SEGUIDA, CRIAMOS UM OBJETO GERADOR CHAMANDO GERARNUMEROSPARES(10), QUE IRÁ GERAR NÚMEROS PARES DE 0 A 10. 

    POR FIM, ITERAMOS SOBRE O OBJETO GERADOR USANDO UM LOOP FOR...OF E IMPRIMIMOS CADA NÚMERO NA SEQUÊNCIA. 

    ISSO NOS PERMITIRÁ GERAR E ITERAR SOBRE NÚMEROS PARES DE FORMA PREGUIÇOSA, OU SEJA, APENAS OS NÚMEROS QUE PRECISAMOS SÃO GERADOS CONFORME SOLICITADO. ISSO É ESPECIALMENTE ÚTIL QUANDO LIDAMOS COM GRANDES CONJUNTOS DE DADOS, ONDE A GERAÇÃO DE TODOS OS VALORES DE UMA VEZ PODE SER INEFICIENTE.
*/